name        'mmickan/hiera_consul'
version     '0.0.1'
source      'https://github.com/mmickan/hiera-consul.git'
author      'Mark Mickan'
summary     'Module for using consul as a hiera backend'
description 'Use consul by Hashicorp, as a hiera backend.  This is a heavily modified fork of Marc Cluet\'s hiera_consul.'
license     'Apache License, Version 2.0'
